### PR TITLE
Updated cheerio

### PR DESCRIPTION
**Pull request by larrybahr**
I needed some of the new features of cheerio, so I updated to the newest stable version 0.22.0. I also updated the development dependencies to include everything needed for testing.

### CODE REVIEW

**Comment by larrybahr** [comment]
@jprichardson can you accept my PR or give me some feedback as to why you are not accepting it

**Comment by jprichardson** [comment]
@larrybahr your commit does more than what it states. Changes tests to asserts, introducing package-lock, modifying styles, etc should all be separate commits. That being said, this project is 5 years old and I have no interest in maintaining it anymore. I'd be happy to transfer it to you and add you as an owner on npm. Sound good?

**Comment by larrybahr** [comment]
You are right. I should have made multiple PR. Sorry about the style change (VS Code auto format must have been on).

The company I work for is currently using this in a project, so owning the project would be great. Thank you.

**Comment by larrybahr** [comment]
Thank you again for the offer to transfer the node-scrap repository, but I no longer need it or the changes I made. Due to how long it has taken to merge this pull request, I started using [puppeteer](https://www.npmjs.com/package/puppeteer). If you would still like my changes please merge them in by the end of next week. After that I am going to close this pull request and remove my repository with the changes.

**Pull request closed without merging**
